// src/components/vue/TableOfContentsWrapper.vue
<script setup lang="ts">
// Your existing script setup
</script>

<template>
  <div class="toc-wrapper hidden md:block">
    <slot />
  </div>
</template>

<style scoped>
.toc-wrapper {
  position: fixed;
  bottom: 30px;
  left: 20px;
  max-height: 60vh;
  overflow-y: auto;
  z-index: 40;
  /* Your existing styles */
}

/* Other existing styles */
</style>

// src/components/react/TableOfContentsWrapper.tsx
"use client";

import React from "react";
import { cn } from "@/lib/utils";

interface TableOfContentsWrapperProps {
  children: React.ReactNode;
  className?: string;
}

export function TableOfContentsWrapper({ 
  children, 
  className 
}: TableOfContentsWrapperProps) {
  return (
    <div 
      className={cn(
        "fixed bottom-[120px] left-5 z-40 max-h-[60vh] overflow-y-auto",
        "hidden md:block",
        "scrollbar-thin scrollbar-thumb-border scrollbar-track-transparent",
        className
      )}
    >
      {children}
    </div>
  );

}
